# Generated by Django 5.2 on 2025-05-12 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_casal', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('hero_title', models.CharField(default='Feliz 5 Meses Meu Amor', max_length=100)),
                ('hero_subtitle', models.CharField(default='Cada dia ao seu lado é uma nova razão para sorrir', max_length=100)),
                ('carta_amor', models.TextField()),
                ('data_inicio', models.DateField()),
                ('footer_title', models.CharField(default='Feliz 5 Meses Meu Amor', max_length=100)),
                ('footer_subtitle', models.CharField(default='Que venham muitos mais meses, anos e décadas de amor, companheirismo e felicidade.', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('imagem', models.ImageField(upload_to='core/img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('history', 'Nossa História em Fotos'), ('hero', 'Hero'), ('moment', 'Momentos'), ('music', 'Musica')], default='history', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.cliente')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagem')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo_audio', models.FileField(upload_to='core/audio/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='musicas',
            field=models.ManyToManyField(related_name='clientes', to='core.musica'),
        ),
    ]
